/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyHostCodeRouteImport } from './routes/lobby/$hostCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyHostCodeRoute = LobbyHostCodeRouteImport.update({
  id: '/lobby/$hostCode',
  path: '/lobby/$hostCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby/$hostCode': typeof LobbyHostCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby/$hostCode': typeof LobbyHostCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby/$hostCode': typeof LobbyHostCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lobby/$hostCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lobby/$hostCode'
  id: '__root__' | '/' | '/lobby/$hostCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyHostCodeRoute: typeof LobbyHostCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$hostCode': {
      id: '/lobby/$hostCode'
      path: '/lobby/$hostCode'
      fullPath: '/lobby/$hostCode'
      preLoaderRoute: typeof LobbyHostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyHostCodeRoute: LobbyHostCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
